In [ ]:

def sieve(n):
    b_list = [True] * (n+1)
    for i in range(2, n+1):
        if b_list[i]:
            for j in range(i*i, n+1, i):
                b_list[j] = False
    primes = [i for i in range(2, n+1) if b_list[i]]
    return primes

print(sieve(50))





[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


In [14]:
import numpy

def np_sieve(n):
    b = numpy.ones(n+1, dtype=numpy.bool)
    print(b)
    b[0:2] = False
    print()
    
    print(b)
    for i in range(2, n+1):
        if b[i]:
            b[i*i::i] = False
    
    return numpy.arange(n+1)[b]

print(np_sieve(50))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]

[False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


In [20]:
import numpy as np
import numpy.random as ran

a = ran.rand(10)

print(a)

a = ran.random(100000)
print('mean : ', np.mean(a))
print('sum : ', np.sum(a))
print('median : ', np.median(a))
print('std : ', np.std(a))

a2 = (a - np.mean(a)) ** 2
print()
print(a2)

result = (np.mean(a2)) ** 0.5
print(result)

print()
print(np.std(a))



[0.16035811 0.77672378 0.90566297 0.14198787 0.09620322 0.32871128
 0.00817314 0.14005886 0.00996058 0.90175185]
mean :  0.5006571855610744
sum :  50065.718556107444
median :  0.5002938127428569
std :  0.28826743413862554

[0.03393506 0.11369481 0.0499968  ... 0.11647711 0.01395293 0.09634916]
0.28826743413862554

0.28826743413862554


In [22]:
import numpy as np
import numpy.random as ran

a = ran.randint(1, 20, (3, 4))
print(a)

print(np.mean(a))
print(np.sum(a))
print(np.std(a))

[[19  1 17  3]
 [ 8  7 13 18]
 [ 5 18  7 16]]
11.0
132
6.244997998398398


In [25]:
import numpy

a = numpy.arange(1, 10).reshape(3, 3)

print(a)

print()

print(numpy.sum(a, axis=0))
print(numpy.sum(a, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[12 15 18]
[ 6 15 24]


In [37]:
import numpy

a = np.fromfunction(lambda r, c: c, (4,5), dtype=numpy.int32)
b_row = numpy.sum(a, axis=1)
b_col = numpy.sum(a, axis=0)

print(a)
print(b_col)
print(b_row)

c = numpy.c_[a, b_row]
print()
print(c)

c2 = numpy.r_[a, [b_col]]
print()

print(c2)



[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[ 0  4  8 12 16]
[10 10 10 10]

[[ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]]

[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 0  4  8 12 16]]


In [40]:
import numpy

def spreadsheet(A):
    AC = numpy.sum(A, axis=1)
    A2 = np.c_[A,AC]
    AR = numpy.sum(A2, axis=0)
    return numpy.r_[A2, [AR]]

arr = np.arange(15).reshape(3, 5)
print(arr)
print()
print(spreadsheet(arr))
    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[  0   1   2   3   4  10]
 [  5   6   7   8   9  35]
 [ 10  11  12  13  14  60]
 [ 15  18  21  24  27 105]]
